spring:
  application:
    name: chat-app-backend
  
  # MongoDB connection properties
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chat-app}
#      uri: mongodb+srv://arnavchauhan5011:9DRxNm5xKwTjddaM@journal.zcayqt9.mongodb.net/?retryWrites=true&w=majority&appName=journal
      database: ${MONGODB_DATABASE:chat-app}
      auto-index-creation: true

google:
  api:
    key: ${GEMINI_API_KEY}
  gemini:
    model: ${GEMINI_MODEL_CODE:gemini-2.5-flash-lite}
  
  # Devtools properties
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  
  # Multipart properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Swagger configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# File storage configuration
file:
  upload-dir: ./uploads/avatars

# Logging configuration
logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
