spring.application.name=chat-app-backend

# MongoDB connection properties
#spring.data.mongodb.uri=mongodb://localhost:27017/chat-app
spring.data.mongodb.uri=mongodb+srv://arnavchauhan5011:9DRxNm5xKwTjddaM@journal.zcayqt9.mongodb.net/?retryWrites=true&w=majority&appName=journal
spring.data.mongodb.database=chat-app
spring.data.mongodb.auto-index-creation=true

# Devtools properties
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Multipart properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# File storage configuration
file.upload-dir=./uploads/avatars

# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n





